# Enforce engine versions in package.json
engineStrict: true

# Enable save-exact
savePrefix: ''

# Delay the installation of newly published versions (minutes)
minimumReleaseAge: 1440

# Dependencies allowed to run install scripts
onlyBuiltDependencies: []
