"use client"

import { Box, Button, Container, TextField } from "@mui/material"
import Head from "next/head"
import { useRouter } from "next/navigation"
import { useEffect } from "react"
import { Controller, useForm } from "react-hook-form"
import { hasToken, setToken } from "../lib/auth"
import AnonymousAppBar from "./app_bar/anonymous_app_bar"

export interface LoginValues {
  token: string
}

export default function LoginForm() {
  const router = useRouter()
  const { control, handleSubmit } = useForm<LoginValues>({
    defaultValues: {
      token: "",
    },
  })

  const onSubmit = (values: LoginValues): void => {
    setToken(values.token)
    router.push("/")
  }

  useEffect(() => {
    if (hasToken()) {
      router.push("/")
    }
  })

  return (
    <div>
      <Head>
        <title>Login - Harmonica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnonymousAppBar />
      <Container component="main" sx={{ mt: 3 }}>
        <Box
          component="form"
          autoComplete="off"
          onSubmit={handleSubmit(onSubmit)}
        >
          <Box>
            <Controller
              name="token"
              control={control}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="JWT Token"
                  type="password"
                  fullWidth
                  required
                />
              )}
            />
          </Box>
          <Box sx={{ mt: 4 }}>
            <Button variant="contained" type="submit">
              Login
            </Button>
          </Box>
        </Box>
      </Container>
    </div>
  )
}
