import Head from 'next/head'
import { hasToken, setToken } from '../lib/auth'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { useForm, Controller } from 'react-hook-form'
import { Box, Button, Container, TextField } from '@mui/material'
import AnonymousAppBar from '../lib/components/app_bar/anonymous_app_bar'

interface LoginValues {
  token: string
}

export default function LoginPage() {
  const router = useRouter()
  const { control, handleSubmit } = useForm<LoginValues>({
    defaultValues: {
      token: ''
    }
  })

  const onSubmit = (values: LoginValues): void => {
    setToken(values.token)
    router.push('/')
  }

  useEffect(() => {
    if (hasToken()) {
      router.push('/')
    }
  })

  return (
    <div>
      <Head>
        <title>Login - Harmonica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnonymousAppBar />
      <Container component="main" sx={{ mt: 3 }}>
        <Box component="form" autoComplete="off" onSubmit={handleSubmit(onSubmit)}>
          <Box>
            <Controller
              name="token"
              control={control}
              render={({ field }) =>
                <TextField
                  {...field}
                  label="JWT Token"
                  fullWidth
                  required
                />
              }
            />
          </Box>
          <Box sx={{ mt: 4 }}>
            <Button variant="contained" type='submit'>
              Login
            </Button>
          </Box>
        </Box>
      </Container>
    </div>
  )
}
